/* The 26 collections on rajkamalprakashan.com/collections, in the live order. `img` = the collection's own tile image (9 have one),
   saved in collections/img/. These open on the live site; the collections in this offer (books-data.js) open here. */
window.RK_LIVE_COLLECTIONS = [
  { slug: "author-of-the-week", name: "Author of the Week", img: true },
  { slug: "award-winners", name: "Award Winners" },
  { slug: "bestsellers", name: "Bestsellers", local: "bestsellers" },
  { slug: "children-books", name: "Children Books", img: true },
  { slug: "deal-of-the-day", name: "Deal of the Day", img: true },
  { slug: "magazine", name: "Magazine" },
  { slug: "must-read", name: "Must Read", img: true },
  { slug: "new-releases", name: "New Releases" },
  { slug: "read-more-save-more", name: "Read More Save More", img: true },
  { slug: "representative-poem", name: "Representative Poem", img: true },
  { slug: "representative-stories", name: "Representative Stories", img: true },
  { slug: "trending-now", name: "Trending Now" },
  { slug: "trending-this-week", name: "Trending this Week" },
  { slug: "world-classic", name: "World Classic" },
  { slug: "akhilesh-ki-charchit-kritiyan", name: "अखिलेश की चर्चित कृतियाँ" },
  { slug: "kitabein-jiname-hain-khoobsurat-prem-kahaniyan", name: "किताबें जिनमें हैं खूबसूरत प्रेम कहानियां" },
  { slug: "kitabein-jo-karti-hain-stree-adhikaron-ki-baat", name: "किताबें जो करती है स्त्री अधिकारों की बात" },
  { slug: "kunwar-narain-ki-charchit-kritiyan", name: "कुँवर नारायण की चर्चित कृतियाँ" },
  { slug: "padhiye-kitabein-jo-batati-hain-kahaniyon-ke-zariye-itihas", name: "पढ़िए किताबें जो बताती हैं कहानियों के ज़रिए इतिहास" },
  { slug: "padhiye-bhartiya-bhashaon-se-hindi-mein-anoodit-upanyas", name: "पढ़िए भारतीय भाषाओं से हिंदी में अनुदित उपन्यास" },
  { slug: "kyu-padhein-ye-6-kitabein", name: "पढ़ें ये 6 नई किताबें" },
  { slug: "bangla-se-anoodit-upanyas", name: "बांग्ला से अनूदित उपन्यास", img: true },
  { slug: "bhagat-singh-ke-jeevan-aur-vicharon-par-adharit-kitabein", name: "भगत सिंह के जीवन और विचारों पर आधारित किताबें" },
  { slug: "shayari-ghazal-ki-kitabein", name: "शायरी-ग़ज़ल की किताबें", img: true },
  { slug: "hindi-divas", name: "हिन्दी दिवस" },
  { slug: "offers", name: "Offers", path: "/offers" }
];
