/* Events from rajkamalprakashan.com/events — titles, descriptions, venues, map links, tags and photos as on each event page.
   The live pages show day + month only; the year (2026) is ours. Upcoming / past is worked out from today's date. */
window.RK_EVENTS = [
  {"id": "kitab-utsav-bareilly", "title": "किताब उत्सव - बरेली", "sub": "पाठक-लेखक संवाद, बातचीत, पाठ, चर्चा, लोकार्पण", "desc": ["राजकमल प्रकाशन समूह द्वारा बरेली शहर में पाँच दिवसीय ‘किताब उत्सव’ का आयोजन किया जा रहा है। यह आयोजन 23-27 अक्टूबर तक विंडरमेयर थियेटर, बलवंत सिंह मार्ग, सिविल लाइन्स, अक्षर विहार के सामने, बरेली में होगा। उत्सव के दौरान पुस्तक प्रदर्शनी के साथ-साथ पाठक-लेखक संवाद, रचना-पाठ, विविध विषयों पर विचार-चर्चाएँ, संगीत प्रस्तुतियाँ और नई पुस्तकों के लोकार्पण जैसे अनेक कार्यक्रम आयोजित किए जाएंगे।"], "start": "2026-10-23T11:00", "end": "2026-10-27T20:00", "city": "Bareilly", "venue": "विंडरमेयर थियेटर, बलवंत सिंह मार्ग, सिविल लाइन्स, अक्षर विहार के सामने, बरेली, Bareilly, Uttar Pradesh", "map": "https://maps.app.goo.gl/mLnmBJpxe5xPtVqTA", "tags": ["Kitab Utsav", "Bareilly", "Literature Festival", "Rajkamal Prakashan", "Hindi Books"], "imgs": ["img/kitab-utsav-bareilly-1.jpg"], "register": true},
  {"id": "book-discussion-misrana-muhalla", "title": "बातचीत : मिसराना मुहल्ला", "sub": "सुधीर चन्द्र के संस्मरणों की किताब 'मिसराना मुहल्ला' पर बातचीत", "desc": ["राजकमल प्रकाशन समूह और अर्थशिला, पटना की साझा पहल परस्पर की दूसरी कड़ी में इतिहासकार सुधीर चन्द्र की नई किताब मिसराना मुहल्ला पर उनसे बातचीत करेंगे आलोचक संजीव कुमार।"], "start": "2026-09-27T18:00", "end": "2026-09-27T19:30", "city": "Patna", "venue": "अर्थशिला, पटना", "map": "https://maps.app.goo.gl/Ya3KtaNeHoDD3zXb7", "tags": ["Book Discussion", "Meet the Author"], "imgs": ["img/book-discussion-misrana-muhalla-1.jpg", "img/book-discussion-misrana-muhalla-2.jpg"], "register": false},
  {"id": "book-discussion-koi-ek-sayeda", "title": "बातचीत : कोई एक सईदा", "sub": "नेहा दीक्षित की किताब 'कोई एक सईदा' पर बातचीत", "desc": ["लेखक-पत्रकार नेहा दीक्षित की बहुचर्चित किताब कोई एक सईदा पर राजकमल प्रकाशन, पटना में उनसे बातचीत करेंगे लेखक-पत्रकार पुष्यमित्र"], "start": "2026-09-21T17:00", "end": "2026-09-21T18:30", "city": "Patna", "venue": "राजकमल प्रकाशन, पटना", "map": "https://maps.app.goo.gl/TWp96GNyBrcFuRya7", "tags": ["Book Discussion", "Meet the Author"], "imgs": ["img/book-discussion-koi-ek-sayeda-1.jpg", "img/book-discussion-koi-ek-sayeda-2.jpg"], "register": false},
  {"id": "kitab-utsav-indore-2026", "title": "किताब उत्सव - इन्दौर", "sub": "पाठक-लेखक संवाद, बातचीत, पाठ, चर्चा, लोकार्पण", "desc": ["राजकमल प्रकाशन समूह द्वारा इंदौर शहर में पाँच दिवसीय ‘किताब उत्सव’ का आयोजन किया जा रहा है। यह आयोजन 4-8 सितम्बर तक अहिल्या केंद्रीय पुस्तकालय परिसर में स्थित प्रीतमलाल दुआ सभागृह में होगा। उत्सव के दौरान भव्य पुस्तक प्रदर्शनी के साथ-साथ पाठक-लेखक संवाद, रचना-पाठ, विविध विषयों पर विचार-चर्चाएँ, संगीत प्रस्तुतियाँ और नई पुस्तकों के लोकार्पण जैसे अनेक कार्यक्रम आयोजित किए जाएंगे।"], "start": "2026-09-04T11:00", "end": "2026-09-08T20:30", "city": "Indore", "venue": "प्रीतमलाल दुआ सभागृह, इन्दौर, मध्य प्रदेश", "map": "https://maps.app.goo.gl/Pk9DToVY4D11YdgHA", "tags": ["Kitab Utsav", "Literary Festival", "Book Exhibition"], "imgs": ["img/kitab-utsav-indore-2026-1.jpg"], "register": false},
  {"id": "meri-maan-meri-gangster-discussion-and-book-signing", "title": "मेरी माँ मेरी गैंगस्टर | बातचीत • बुक साइनिंग", "sub": "अरुंधति रॉय की किताब 'मेरी माँ मेरी गैंगस्टर' पर बातचीत और बुक साइनिंग", "desc": ["'मेरी माँ मेरी गैंगस्टर' की लेखक अरुंधति रॉय और अनुवादक प्रभात सिंह से उर्मिलेश और अर्जुमंद आरा की बातचीत। अंशपाठ: अन्नुप्रिया।"], "start": "2026-08-03T18:00", "end": "2026-08-03T20:00", "city": "New Delhi", "venue": "मल्टीपर्पज़ हॉल, इंडिया इंटरनेशनल सेंटर, नई दिल्ली", "map": "https://maps.app.goo.gl/xhoNz8Ltt6givvVf6", "tags": ["Discussion", "Book Signing"], "imgs": ["img/meri-maan-meri-gangster-discussion-and-book-signing-1.jpg"], "register": false},
  {"id": "meri-maan-meri-gangster-book-signing", "title": "मेरी माँ मेरी गैंगस्टर | बुक साइनिंग", "sub": "अरुंधति रॉय द्वारा बुक साइनिंग", "desc": ["अरुंधति रॉय अपनी किताब 'मेरी माँ मेरी गैंगस्टर' के लोकार्पण के अगले दिन रविवार को पटना में अशोक राजपथ स्थित राजकमल प्रकाशन के शाखा कार्यालय में पाठकों से रूबरू होंगी। इस अवसर पर लेखक के साथ किताब के अनुवादक प्रभात सिंह भी मौजूद रहेंगे।"], "start": "2026-07-19T13:30", "end": "2026-07-19T15:30", "city": "Patna", "venue": "राजकमल प्रकाशन, अशोक राजपथ, पटना, बिहार", "map": "https://maps.app.goo.gl/gtXLBc3h42Nyfy7WA", "tags": ["Book Signing"], "imgs": ["img/meri-maan-meri-gangster-book-signing-1.jpg"], "register": false},
  {"id": "meri-maan-meri-gangster-book-launch-and-discussion", "title": "मेरी माँ मेरी गैंगस्टर | लोकार्पण • बातचीत", "sub": "अरुंधति रॉय की किताब ‘मेरी माँ मेरी गैंगस्टर’ का लोकार्पण और बातचीत", "desc": ["अरुंधति रॉय की बहुप्रशंसित किताब ‘मदर मैरी कम्स टू मी’ का हिन्दी संस्करण ‘मेरी माँ मेरी गैंगस्टर’ शीर्षक से राजकमल प्रकाशन द्वारा प्रकाशित किया जा रहा है। इसका हिन्दी अनुवाद प्रभात सिंह ने किया है। किताब का लोकार्पण 18 जुलाई 2026 को अर्थशिला, पटना में आयोजित एक विशेष समारोह में होगा। यह कार्यक्रम राजकमल प्रकाशन समूह और अर्थशिला की साझा पहल ‘परस्पर: संवाद की सबरंगी दुनिया’ शृंखला का पहला आयोजन होगा।", "लोकार्पण समारोह में लेखक अरुंधति रॉय और अनुवादक प्रभात सिंह समेत साहित्यिक-सांस्कृतिक क्षेत्र की कई प्रतिष्ठित हस्तियाँ उपस्थित रहेंगी। इस अवसर पर किताब और उसके विभिन्न सामाजिक-सांस्कृतिक पहलुओं पर कथाकार प्रत्यक्षा लेखक और अनुवादक से बातचीत करेंगी।"], "start": "2026-07-18T18:00", "end": "2026-07-18T19:30", "city": "Patna", "venue": "अर्थशिला, पटना, बिहार", "map": "https://maps.app.goo.gl/jMdsQ3enbFQXLJ5m9?g_st=ac", "tags": ["Book Launch", "Discussion", "Book Signing"], "imgs": ["img/meri-maan-meri-gangster-book-launch-and-discussion-1.jpg", "img/meri-maan-meri-gangster-book-launch-and-discussion-2.jpg", "img/meri-maan-meri-gangster-book-launch-and-discussion-3.jpg", "img/meri-maan-meri-gangster-book-launch-and-discussion-4.jpg"], "register": false},
  {"id": "dastan-e-guru-dutt-book-launch-and-discussion", "title": "दास्तान-ए-गुरुदत्त | लोकार्पण • बातचीत", "sub": "महमूद फ़ारूक़ी की किताब 'दास्तान-ए-गुरुदत्त' का लोकार्पण और परिचर्चा", "desc": [], "start": "2026-05-20T19:00", "end": "2026-05-20T21:00", "city": "New Delhi", "venue": "इंडिया हैबिटेट सेंटर, नई दिल्ली", "map": null, "tags": ["Book Launch", "Discussion"], "imgs": ["img/dastan-e-guru-dutt-book-launch-and-discussion-1.jpg", "img/dastan-e-guru-dutt-book-launch-and-discussion-2.jpg"], "register": false}
];
window.RK_EVENT_FORM = { categories: [["student", "विद्यार्थी / Student"], ["author", "लेखक / Author"], ["press", "मीडिया / प्रेस — Media / Press"], ["reader", "पुस्तक प्रेमी / Book Lover"]],
  heard: [["social", "सोशल मीडिया / Social Media"], ["friends", "मित्र या परिवार / Friends & Family"], ["news", "समाचार-पत्र / Newspaper & News"], ["invite", "निमंत्रण / Invitation"], ["other", "अन्य / Other (Please specify)"]] };
